name: Print_hello
on:
  push:
    branches: [main, master]

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "hello world"
      - name: Print world
        run: echo "world"
